name: Run Cypress Tests

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 10AM Malaysia Time (UTC+8)
  push:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout repo
        uses: actions/checkout@v3

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: npm install

      - name: 🧪 Run Cypress tests
        run: npx cypress run
