name: Run Cypress Tests

on:
  schedule:
    - cron: '0 18 * * *'  # 2AM Malaysia Time (MYT = UTC+8)
  push:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: install dependencies
        run: npm ci

      - name: run Cypress tests with Mochawesome
        run: |
          chmod +x ./node_modules/.bin/cypress
          npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/reports,overwrite=true,html=true,json=false"

      - name: send HTML test report
        if: always() 
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.mailersend.net
          server_port: 587
          secure: false
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ job.status == 'success' && '✅ Cypress Tests Passed' || '❌ Cypress Tests Failed' }}
          to: ${{ secrets.EMAIL_TO }}
          from: QA Bot <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Cypress test run complete. See attached HTML report.
            View this run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          attachments: cypress/reports/mochawesome.html
