name: Run Cypress Tests

on:
  schedule:
    - cron: '0 18 * * *'  #2am malaysia time
  push:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: install dependencies
        run: npm install

      - name: download cypress binary
        run: npx cypress install

      - name: run cypress tests
        run: npx cypress run

      - name: 📤 Send test report via email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 🧪 Cypress Test Results
          to: ${{ secrets.EMAIL_TO }}
          from: Cypress Bot <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Test run complete. Report attached.
            Summary: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            attachments: cypress/reports/mochawesome-report.html      
