name: Run Cypress Tests

on:
  schedule:
    - cron: '0 18 * * *'  #to send daily email at 2am malaysia time 
  push:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: install dependencies
        run: npm install

      - name: download cypress binary
        run: npx cypress install

      - name: run cypress tests
        run: npx cypress run

      - name: send HTML test report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.mailersend.net
          server_port: 587
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 🚀 Cypress Daily Report
          to: ${{ secrets.EMAIL_TO }}
          from: QA Bot <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Cypress test run complete. See attached report.
          attachments: cypress/reports/mochawesome-report.html