name: Run Cypress Tests

on:
  schedule:
    - cron: '0 18 * * *'  # 2AM Malaysia time (UTC+8)
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: install mochawesome-merge
        run: npm install -g mochawesome-merge

      - name: install dependencies
        run: npm ci

      - name: clean previous mochawesome reports
        run: rm -rf cypress/reports/*

      - name: run Cypress with Mochawesome
        run: |
          chmod +x ./node_modules/.bin/cypress
          npx cypress run --reporter mochawesome
        continue-on-error: true

      - name: merge mochawesome reports
        run: |
          npx mochawesome-merge cypress/reports/*.json > cypress/reports/merged.json

      - name: set email subject based on test results
        id: subject
        run: |
            FAIL_COUNT=$(jq '[.results[].suites[].tests[] | select(.fail == true)] | length' cypress/reports/merged.json)
            if [ "$FAIL_COUNT" -gt 0 ]; then
              echo "value=❌ Cypress Tests Failed ($FAIL_COUNT failed)" >> $GITHUB_OUTPUT
            else
              echo "value=✅ Cypress Tests Passed" >> $GITHUB_OUTPUT
            fi
        

      - name: Extract Summary for HTML
        id: summary
        run: |
            echo "summary<<EOF" >> $GITHUB_OUTPUT
            echo "<h2 style='color: #333; font-family: Arial, sans-serif;'>Daily Regression Test Summary ⭐</h2>" >> $GITHUB_OUTPUT
            echo "<p style='font-family: Arial, sans-serif; font-size: 16px;'>Hi team,</p>" >> $GITHUB_OUTPUT
            echo "<p style='font-family: Arial, sans-serif; font-size: 16px;'>Below is the latest automated regression test report from our scheduled workflow run:</p>" >> $GITHUB_OUTPUT
        
            echo "<table border='1' cellpadding='10' cellspacing='0' style='border-collapse: collapse; width: 70%; font-family: Arial, sans-serif; color:#333;'>" >> $GITHUB_OUTPUT
            echo "<thead style='background-color:#4CAF50; color: white; text-align: left; font-size: 16px;'>" >> $GITHUB_OUTPUT
            echo "<tr><th style='padding: 12px;'>Spec File</th><th style='padding: 12px;'>✅ Passed</th><th style='padding: 12px;'>❌ Failed</th></tr></thead><tbody>" >> $GITHUB_OUTPUT
        
            jq -r '
              .results[] |
              "<tr style=\"background-color:#f9f9f9;\"><td style=\"padding: 8px; border: 1px solid#ddd;\">" + .file + "</td><td style=\"padding: 8px; border: 1px solid#ddd;\">" +
              ([.suites[].tests[] | select(.pass == true)] | length | tostring) +
              "</td><td style=\"padding: 8px; border: 1px solid#ddd;\">" +
              ([.suites[].tests[] | select(.fail == true)] | length | tostring) +
              "</td></tr>"
            ' cypress/reports/merged.json >> $GITHUB_OUTPUT
        
            echo "</tbody></table>" >> $GITHUB_OUTPUT
            echo "<br>" >> $GITHUB_OUTPUT
            echo "<p style='font-family: Arial, sans-serif; font-size: 16px;'>🔗 <a href=\"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\" style='color:#4CAF50; text-decoration: none;'>View full test run on GitHub</a></p>" >> $GITHUB_OUTPUT
            echo "<p style='font-family: Arial, sans-serif; font-size: 14px; margin-top: 20px;'>—<br><em>This is an automated email from Cypress CI.</em></p>" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
        
      - name: send test report via email
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.gmail.com
            server_port: 465
            secure: true
            username: ${{ secrets.EMAIL_USERNAME }}
            password: ${{ secrets.EMAIL_PASSWORD }}  
            subject: ${{ steps.subject.outputs.value }}
            to: ${{ secrets.EMAIL_TO }}
            from: Cypress Bot <${{ secrets.EMAIL_USERNAME }}>
            html_body: ${{ steps.summary.outputs.summary }}
        
#updated on 9/4/2025
